wget https://user.ceng.metu.edu.tr/~e1942309/nar.zip;
sudo apt-get update;
sudo apt-get -y install unzip;
sudo apt-get install libboost-all-dev;
sudo apt-get -y install libcrypto++-dev;
sudo add-apt-repository ppa:ubuntu-toolchain-r/test;
sudo apt-get update;
sudo apt-get -y install gcc-5 g++-5;
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5;
sudo apt-get -y install make;
sudo apt-get -y install libpng-dev;
sudo apt-get -y install zlib1g-dev;
unzip nar.zip;
mkdir ~/nar/build;
cd ~nar/build;
cmake ..;
make;
sudo mkdir /root/.nar;
sudo mkdir /root/.nar/chunks;
sudo echo -e "NAR_FOLDER=/root/.nar/\nFILE_FOLDER=/root/.nar/chunks/\nSERVER_IP=35.187.10.23\nSERVER_PORT=16670\nMACHINE_ID=" > /root/.nar/config;
echo "alias nar='~/nar/narnode/narcli'" >> ~/.bashrc;
source ~/.bashrc;
