all:
	g++ client.cpp -O3 -o cli -lboost_system -lcrypto -lssl -lpthread
	g++ server.cpp -O3 -o srv -lboost_system -lcrypto -lssl -lpthread

srv:
	g++ server.cpp -O3 -o srv -lboost_system -lcrypto -lssl -lpthread
